changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change

    - title: Bug Fixes
      labels:
        - bug

    - title: New Features
      labels:
        - enhancement
      exclude:
        labels:
          - documentation
          - dependencies

    - title: Documentation
      labels:
        - documentation

    - title: Internal Changes
      labels:
        - chore
        - refactor

    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies

    - title: Dependency Updates
      labels:
        - dependencies
