// Copyright 2025 Taidge contributors
//
// SPDX-License-Identifier: Apache-2.0

//! Code generator that fetches IANA JOSE and OAuth registry CSVs and
//! emits typed Rust enums into the `pasion-iana` crate.

use std::{collections::HashMap, fmt::Display};

use camino::{Utf8Path, Utf8PathBuf};
use reqwest::Client;
use tokio::io::AsyncWriteExt;
use tracing::Level;

mod generation;
pub mod jose;
pub mod oauth;
pub mod traits;

use self::traits::{EnumEntry, EnumMember, Section};

// ── File builder ─────────────────────────────────────────────────────

/// Accumulates sections and members from one or more IANA registries,
/// then renders them as a single Rust source file.
#[derive(Debug)]
struct RegistryFile {
    client: Client,
    registry_name: &'static str,
    registry_url: &'static str,
    sections: Vec<Section>,
    members: HashMap<&'static str, Vec<EnumMember>>,
}

/// Resolve a workspace-relative path to an absolute path.
fn resolve_path(relative: impl AsRef<Utf8Path>) -> Utf8PathBuf {
    let manifest_dir = Utf8Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Utf8Path::parent)
        .expect("workspace root");
    workspace_root.join(relative)
}

impl RegistryFile {
    #[tracing::instrument(skip(client))]
    fn new(
        registry_name: &'static str,
        registry_url: &'static str,
        client: Client,
    ) -> Self {
        tracing::info!("Generating file from IANA registry");
        Self {
            client,
            registry_name,
            registry_url,
            sections: Vec::new(),
            members: HashMap::new(),
        }
    }

    /// Fetch a CSV-based enum entry type and merge its sections/members.
    #[tracing::instrument(skip_all, fields(url))]
    async fn load<T: EnumEntry>(mut self) -> anyhow::Result<Self> {
        tracing::Span::current().record("url", T::URL);
        self.sections.extend(T::sections());
        for (key, member) in T::fetch(&self.client).await? {
            self.members.entry(key).or_default().push(member);
        }
        Ok(self)
    }

    /// Write the generated Rust source to `path`.
    #[tracing::instrument(skip_all)]
    async fn write(&self, path: impl AsRef<Utf8Path>) -> anyhow::Result<()> {
        let content = format!("{self}");
        let mut file = tokio::fs::OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(path.as_ref())
            .await?;
        tracing::info!("Writing file");
        file.write_all(content.as_bytes()).await?;
        Ok(())
    }
}

impl Display for RegistryFile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "#![allow(clippy::doc_markdown)]\n\
             \n\
             //! Enums from the {:?} IANA registry\n\
             //! See <{}>\n\
             \n\
             // Do not edit this file manually",
            self.registry_name, self.registry_url,
        )?;

        for section in &self.sections {
            let Some(list) = self.members.get(section.key) else {
                continue;
            };

            let exhaustive = section.key == "OAuthAuthorizationEndpointResponseType";
            writeln!(f)?;

            generation::struct_def(f, section, list, exhaustive)?;
            writeln!(f)?;
            generation::display_impl(f, section, list, exhaustive)?;
            writeln!(f)?;
            generation::from_str_impl(f, section, list, exhaustive)?;
            writeln!(f)?;
            generation::serde_impl(f, section)?;
            writeln!(f)?;
            generation::json_schema_impl(f, section, list)?;
        }

        Ok(())
    }
}

// ── Generator entry-points ───────────────────────────────────────────

#[tracing::instrument(skip_all, fields(%path))]
async fn generate_jose(
    client: &Client,
    path: impl AsRef<Utf8Path> + std::fmt::Display,
) -> anyhow::Result<()> {
    let abs = resolve_path(path);
    RegistryFile::new(
        "JSON Object Signing and Encryption",
        "https://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml",
        client.clone(),
    )
    .load::<jose::WebEncryptionSignatureAlgorithm>()
    .await?
    .load::<jose::WebEncryptionCompressionAlgorithm>()
    .await?
    .load::<jose::WebKeyType>()
    .await?
    .load::<jose::WebKeyEllipticCurve>()
    .await?
    .load::<jose::WebKeyUse>()
    .await?
    .load::<jose::WebKeyOperation>()
    .await?
    .write(abs)
    .await
}

#[tracing::instrument(skip_all, fields(%path))]
async fn generate_oauth(
    client: &Client,
    path: impl AsRef<Utf8Path> + std::fmt::Display,
) -> anyhow::Result<()> {
    let abs = resolve_path(path);
    RegistryFile::new(
        "OAuth Parameters",
        "https://www.iana.org/assignments/jose/jose.xhtml",
        client.clone(),
    )
    .load::<oauth::AccessTokenType>()
    .await?
    .load::<oauth::AuthorizationEndpointResponseType>()
    .await?
    .load::<oauth::TokenTypeHint>()
    .await?
    .load::<oauth::TokenEndpointAuthenticationMethod>()
    .await?
    .load::<oauth::PkceCodeChallengeMethod>()
    .await?
    .write(abs)
    .await
}

// ── Main ─────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_max_level(Level::INFO)
        .pretty()
        .init();

    rustls::crypto::aws_lc_rs::default_provider()
        .install_default()
        .unwrap();

    #[expect(
        clippy::disallowed_methods,
        reason = "reqwest::Client::new is fine in the codegen tool"
    )]
    let client = Client::new();

    let iana_root = Utf8Path::new("crates/iana/");

    generate_jose(&client, iana_root.join("src/jose.rs")).await?;
    generate_oauth(&client, iana_root.join("src/oauth.rs")).await?;

    Ok(())
}
