[package]
name = "pasion-jose"
description = "JSON Object Signing and Encryption (JWT & co) utilities"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
# Serialization
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true

# Cryptographic primitives
digest.workspace = true
ecdsa.workspace = true
ed25519-dalek.workspace = true
elliptic-curve.workspace = true
generic-array.workspace = true
hmac.workspace = true
rand.workspace = true
rsa.workspace = true
sha2.workspace = true
signature.workspace = true

# Elliptic curves
k256.workspace = true
p256.workspace = true
p384.workspace = true
p521.workspace = true
sec1.workspace = true

# Encoding & misc
base64ct.workspace = true
chrono.workspace = true
schemars.workspace = true
thiserror.workspace = true
url.workspace = true

# Workspace crates
pasion-iana.workspace = true

[dev-dependencies]
insta.workspace = true
rand_chacha.workspace = true
