[package]
name = "pasion"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

build = "build.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
camino.workspace = true
chrono.workspace = true
clap.workspace = true
console.workspace = true
crc.workspace = true
deadpool.workspace = true
dialoguer.workspace = true
dotenvy.workspace = true
figment.workspace = true
futures-util.workspace = true
headers.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
ipnetwork.workspace = true
itertools.workspace = true
listenfd.workspace = true
rand.workspace = true
rand_chacha.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
diesel.workspace = true
diesel-async.workspace = true
diesel_migrations.workspace = true
tokio.workspace = true
tokio-util.workspace = true
salvo.workspace = true
url.workspace = true
zeroize.workspace = true

tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry-http.workspace = true
opentelemetry-instrumentation-process.workspace = true
opentelemetry-instrumentation-tokio.workspace = true
opentelemetry-jaeger-propagator.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-prometheus-text-exporter.workspace = true
opentelemetry-resource-detectors.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry-stdout.workspace = true
opentelemetry_sdk.workspace = true
sentry.workspace = true
sentry-tracing.workspace = true

pasion-backend.workspace = true
pasion-config.workspace = true
pasion-data.workspace = true
pasion-messaging.workspace = true
pasion-i18n.workspace = true
pasion-keystore.workspace = true
pasion-matrix.workspace = true
pasion-matrix-palpo.workspace = true
pasion-policy.workspace = true
pasion-tasks.workspace = true
pasion-templates.workspace = true

tokio-postgres.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
sd-notify.workspace = true

[build-dependencies]
anyhow.workspace = true
vergen-gitcl.workspace = true

[features]
# Features used for the prebuilt binaries
dist = ["pasion-config/dist"]

# Features used in the Docker image
docker = ["pasion-config/docker"]

# Policy engine backends
cedar = ["pasion-backend/cedar"]
remote = ["pasion-backend/remote"]
