[application]
name = "pasion-frontend"
default_platform = "web"

[web.app]
title = "Pasion"

[web.resource]
style = ["assets/main.css"]

[web.resource.dev]
style = ["assets/main.css"]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[server]
port = 8182

[[web.proxy]]
backend = "http://localhost:8080/api"

[[web.proxy]]
backend = "http://localhost:8080/upstream"

[[web.proxy]]
backend = "http://localhost:8080/authorize"

[[web.proxy]]
backend = "http://localhost:8080/.well-known"

[[web.proxy]]
backend = "http://localhost:8080/oauth2"

[[web.proxy]]
backend = "http://localhost:8080/health"
