//! Pasion backend — HTTP server, state management, lifecycle, and telemetry.
//!
//! This crate provides the runtime infrastructure for the Pasion platform.
//! It is consumed by the CLI binary (`pasion`) and can also be used to
//! embed Pasion as a library.

#![allow(
    // This is an application crate with a large HTTP surface. Requiring public-library
    // documentation conventions on every handler obscures the actionable lints.
    clippy::pedantic,
    // The backend is the integration boundary that owns wall-clock, random-ID, and
    // outbound HTTP access. Lower layers continue to require injected abstractions.
    clippy::disallowed_methods,
    // Handler outcome enums intentionally carry response-specific payloads. Boxing
    // individual variants would complicate the API for no measurable benefit.
    clippy::large_enum_variant,
    // Service entry points pass explicit dependencies instead of hiding them in
    // ambient state, which occasionally exceeds Clippy's argument-count heuristic.
    clippy::too_many_arguments,
    // `BoxClock` erases the concrete `SystemClock` type, so `Box::default()` cannot
    // replace `Box::new(SystemClock::default())`.
    clippy::box_default
)]

pub mod app_state;
pub mod error;
pub mod lifecycle;
/// Network listener infrastructure: TCP/Unix sockets, TLS, and PROXY protocol.
pub mod listener;
/// OpenID Connect client library.
pub mod oidc_client;
mod outbound_http;
/// Salvo web-framework utilities: middleware, extractors, and helpers.
pub mod salvo_utils;
pub mod server;
pub mod services;
pub mod storage;
pub mod sync;
pub mod telemetry;
pub mod totp;
pub mod util;

/// HTTP request handlers, service modules, and flow engine.
#[allow(
    // Some salvo handlers need that
    clippy::unused_async,
    // Because of how salvo handlers work, we sometime have take many arguments
    clippy::too_many_arguments,
    // Code generated by tracing::instrument trigger this when returning an `impl Trait`
    // See https://github.com/tokio-rs/tracing/issues/2613
    clippy::let_with_type_underscore,
)]
pub mod handlers;

use std::sync::OnceLock;

pub use crate::{
    error::{AppError, AppResult, CreatedJsonResult, JsonResult},
    outbound_http::reqwest_client,
};

/// Application version string, set once at startup by the binary crate.
static VERSION: OnceLock<&'static str> = OnceLock::new();

/// Set the application version string.
///
/// Must be called exactly once, before any code that reads `version()`.
/// Typically called from `main()` in the CLI binary.
///
/// # Panics
///
/// Panics if called more than once.
pub fn set_version(v: &'static str) {
    VERSION
        .set(v)
        .expect("pasion_backend::set_version called more than once");
}

/// Get the application version string.
///
/// # Panics
///
/// Panics if [`set_version`] has not been called yet.
pub fn version() -> &'static str {
    VERSION
        .get()
        .expect("pasion_backend::set_version was not called")
}
