//! Pasion backend — HTTP server, state management, lifecycle, and telemetry.
//!
//! This crate provides the runtime infrastructure for the Pasion platform.
//! It is consumed by the CLI binary (`pasion`) and can also be used to
//! embed Pasion as a library.

pub mod app_state;
pub mod lifecycle;
/// Network listener infrastructure: TCP/Unix sockets, TLS, and PROXY protocol.
pub mod listener;
/// OpenID Connect client library.
pub mod oidc_client;
/// Salvo web-framework utilities: middleware, extractors, and helpers.
pub mod salvo_utils;
pub mod server;
pub mod services;
pub mod sync;
pub mod telemetry;
pub mod util;

/// HTTP request handlers, service modules, and flow engine.
#[allow(
    // Some salvo handlers need that
    clippy::unused_async,
    // Because of how salvo handlers work, we sometime have take many arguments
    clippy::too_many_arguments,
    // Code generated by tracing::instrument trigger this when returning an `impl Trait`
    // See https://github.com/tokio-rs/tracing/issues/2613
    clippy::let_with_type_underscore,
)]
pub mod handlers;

use std::sync::OnceLock;

/// Application version string, set once at startup by the binary crate.
static VERSION: OnceLock<&'static str> = OnceLock::new();

/// Set the application version string.
///
/// Must be called exactly once, before any code that reads `version()`.
/// Typically called from `main()` in the CLI binary.
///
/// # Panics
///
/// Panics if called more than once.
pub fn set_version(v: &'static str) {
    VERSION
        .set(v)
        .expect("pasion_backend::set_version called more than once");
}

/// Get the application version string.
///
/// # Panics
///
/// Panics if [`set_version`] has not been called yet.
pub fn version() -> &'static str {
    VERSION
        .get()
        .expect("pasion_backend::set_version was not called")
}
