[package]
name = "pasion-backend"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
chrono.workspace = true
crc.workspace = true
deadpool.workspace = true
futures-util.workspace = true
headers.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
ipnetwork.workspace = true
listenfd.workspace = true
pin-project-lite.workspace = true
rand.workspace = true
rand_chacha.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
socket2.workspace = true
diesel.workspace = true
diesel-async.workspace = true
diesel_migrations.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
salvo.workspace = true
url.workspace = true
zeroize.workspace = true

tracing.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry-http.workspace = true
opentelemetry-instrumentation-process.workspace = true
opentelemetry-instrumentation-tokio.workspace = true
opentelemetry-jaeger-propagator.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-prometheus-text-exporter.workspace = true
opentelemetry-resource-detectors.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry-stdout.workspace = true
opentelemetry_sdk.workspace = true
sentry.workspace = true
sentry-tracing.workspace = true

pasion-config.workspace = true
pasion-context.workspace = true
pasion-data-model.workspace = true
pasion-messaging.workspace = true
pasion-http.workspace = true
pasion-i18n.workspace = true
pasion-iana.workspace = true
pasion-jose.workspace = true
pasion-keystore.workspace = true
pasion-matrix.workspace = true
pasion-matrix-palpo.workspace = true
pasion-policy.workspace = true
pasion-storage.workspace = true
pasion-storage-pg.workspace = true
pasion-tasks.workspace = true
pasion-templates.workspace = true
oauth2-types.workspace = true

argon2.workspace = true
async-trait.workspace = true
base64ct.workspace = true
bcrypt.workspace = true
camino.workspace = true
cookie.workspace = true
elliptic-curve.workspace = true
form_urlencoded.workspace = true
governor.workspace = true
hex.workspace = true
icu_locid.workspace = true
icu_normalizer.workspace = true
indexmap.workspace = true
language-tags.workspace = true
lettre.workspace = true
mime.workspace = true
minijinja.workspace = true
minijinja-contrib.workspace = true
p256.workspace = true
pbkdf2.workspace = true
pkcs8.workspace = true
psl.workspace = true
schemars.workspace = true
serde.workspace = true
serde_urlencoded.workspace = true
serde_with.workspace = true
sha2.workspace = true
tokio-postgres.workspace = true
ulid.workspace = true
uuid.workspace = true
woothee.workspace = true
zxcvbn.workspace = true

[target.'cfg(unix)'.dependencies]
sd-notify.workspace = true

[dev-dependencies]
cookie_store.workspace = true
insta.workspace = true
tokio-test.workspace = true
tracing-subscriber.workspace = true
wiremock.workspace = true

[build-dependencies]
anyhow.workspace = true
vergen-gitcl.workspace = true

[features]
# Policy engine backends
cedar = ["pasion-policy/cedar"]
remote = ["pasion-policy/remote"]
