[package]
name = "pasion-handlers"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
async-trait.workspace = true
base64ct.workspace = true
bcrypt.workspace = true
camino.workspace = true
chrono.workspace = true
elliptic-curve.workspace = true
futures-util.workspace = true
governor.workspace = true
headers.workspace = true
hex.workspace = true
http.workspace = true
hyper.workspace = true
icu_normalizer.workspace = true
indexmap.workspace = true
ipnetwork.workspace = true
lettre.workspace = true
mime.workspace = true
minijinja-contrib.workspace = true
minijinja.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry.workspace = true
pbkdf2.workspace = true
pkcs8.workspace = true
psl.workspace = true
rand_chacha.workspace = true
rand.workspace = true
reqwest.workspace = true
rustls.workspace = true
schemars.workspace = true
sentry.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
serde_with.workspace = true
serde.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
salvo.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
url.workspace = true
zeroize.workspace = true

pasion-salvo-utils.workspace = true
pasion-config.workspace = true
pasion-context.workspace = true
pasion-data-model.workspace = true
pasion-email.workspace = true
pasion-http.workspace = true
pasion-i18n.workspace = true
pasion-iana.workspace = true
pasion-jose.workspace = true
pasion-keystore.workspace = true
pasion-matrix.workspace = true
pasion-oidc-client.workspace = true
pasion-policy.workspace = true
pasion-router.workspace = true
pasion-storage.workspace = true
pasion-storage-pg.workspace = true
pasion-tasks.workspace = true
pasion-templates.workspace = true
oauth2-types.workspace = true
woothee.workspace = true
zxcvbn.workspace = true

[dev-dependencies]
insta.workspace = true
tracing-subscriber.workspace = true
cookie_store.workspace = true
sqlx.workspace = true
wiremock.workspace = true
