[package]
name = "pasion-salvo-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64ct.workspace = true
chrono.workspace = true
cookie.workspace = true
headers.workspace = true
http.workspace = true
icu_locid.workspace = true
mime.workspace = true
rand.workspace = true
reqwest.workspace = true
salvo.workspace = true
sentry.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
ulid.workspace = true

oauth2-types.workspace = true
pasion-data-model.workspace = true
pasion-http.workspace = true
pasion-iana.workspace = true
pasion-jose.workspace = true
pasion-keystore.workspace = true
pasion-storage.workspace = true
pasion-templates.workspace = true
