[package]
name = "pasion-templates"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
camino.workspace = true
chrono.workspace = true
http.workspace = true
minijinja-contrib.workspace = true
minijinja.workspace = true
rand.workspace = true
rand_chacha.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
url.workspace = true
v_htmlescape.workspace = true
walkdir.workspace = true

oauth2-types.workspace = true
pasion-data-model.workspace = true
pasion-i18n.workspace = true
pasion-iana.workspace = true
pasion-policy.workspace = true
pasion-router.workspace = true
pasion-spa.workspace = true

[dev-dependencies]
rand_chacha.workspace = true
