[package]
name = "pasion-tasks"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
cron.workspace = true
opentelemetry-semantic-conventions.workspace = true
opentelemetry.workspace = true
rand_chacha.workspace = true
rand.workspace = true
serde_json.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing-opentelemetry.workspace = true
tracing.workspace = true
ulid.workspace = true

pasion-context.workspace = true
pasion-data-model.workspace = true
pasion-email.workspace = true
pasion-i18n.workspace = true
pasion-matrix.workspace = true
pasion-router.workspace = true
pasion-storage-pg.workspace = true
pasion-storage.workspace = true
pasion-templates.workspace = true
