name: Test Coverage Reports

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: "true"
  CARGO_TERM_COLOR: always

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: false

jobs:
  rust:
    name: Gather Rust coverage data
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_GHA_ENABLED: "true"

    services:
      postgres:
        image: docker.io/library/postgres:15.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Fetch repository
        uses: actions/checkout@v6

      - name: Set up Rust with llvm-tools
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Configure sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Set up grcov
        uses: taiki-e/install-action@v2
        with:
          tool: grcov

      - name: Execute tests with coverage instrumentation
        run: |
          cargo test --no-fail-fast --workspace
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
          LLVM_PROFILE_FILE: "cargo-test-%p-%m.profraw"
          RUSTFLAGS: "-Cinstrument-coverage --cfg tokio_unstable"

      - name: Produce grcov lcov report
        run: |
          mkdir -p target/coverage
          grcov . --binary-path ./target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/coverage/tests.lcov

      - name: Submit Rust coverage to codecov.io
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/coverage/*.lcov
          flags: unit
